language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-27
    - android-26
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script: ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)